parameters:
#    scraip_study.example.class: Scraip\StudyBundle\Example

services:
#    scraip_study.example:
#        class: %scraip_study.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
